import algorithm


class Color:
    reset = "\033[0m"
    bold = "\033[1m"
    dim = "\033[2m"

    red = "\033[31m"
    green = "\033[32m"
    yellow = "\033[33m"
    blue = "\033[34m"
    magenta = "\033[35m"
    cyan = "\033[36m"
    white = "\033[37m"


def ascii_landing():

    algorithm.clear()

    print(
        f"{Color.cyan}{Color.dim}\n"
        "    ╔══════════════════════════════════════════════════"
        "══════════════════════════════╗\n"
        "    ║                                                  "
        "                                ║\n"
        f"    ║{Color.magenta}{Color.bold}"
        "      █████╗     ███╗   ███╗ █████╗ ███████╗███████╗"
        f"    ██╗███╗   ██╗ ██████╗     {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.magenta}{Color.bold}"
        "     ██╔══██╗    ████╗ ████║██╔══██╗╚══███╔╝██╔════╝"
        f"    ██║████╗  ██║██╔════╝     {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.magenta}{Color.bold}"
        "     ███████║    ██╔████╔██║███████║  ███╔╝ █████╗  "
        f"    ██║██╔██╗ ██║██║  ███╗    {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.magenta}{Color.bold}"
        "     ██╔══██║    ██║╚██╔╝██║██╔══██║ ███╔╝  ██╔══╝  "
        f"    ██║██║╚██╗██║██║   ██║    {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.magenta}{Color.bold}"
        "     ██║  ██║    ██║ ╚═╝ ██║██║  ██║███████╗███████╗"
        f"    ██║██║ ╚████║╚██████╔╝    {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.magenta}{Color.bold}"
        "     ╚═╝  ╚═╝    ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝"
        f"    ╚═╝╚═╝  ╚═══╝ ╚═════╝     {Color.cyan}{Color.dim}║\n"
        "    ║                                                  "
        "                                ║\n"
        f"    ║{Color.yellow}{Color.bold}"
        "                           🧩  A - M A Z E - I N G  🧩"
        f"                            {Color.cyan}{Color.dim}║\n"
        "    ║                                                  "
        "                                ║\n"
        f"    ║{Color.white}"
        "                         Created by brouane / bmarbouh"
        f"                            {Color.cyan}{Color.dim}║\n"
        "    ╠══════════════════════════════════════════════════"
        "══════════════════════════════╣\n"
        "    ║                                                  "
        "                                ║\n"
        f"    ║{Color.green}"
        "   ● Generate perfect & imperfect mazes               "
        f"                            {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.green}"
        "   ● Visualize solving algorithms                      "
        f"                          {Color.cyan}{Color.dim}║\n"
        f"    ║{Color.green}"
        "   ● Optional colored rendering                        "
        f"                          {Color.cyan}{Color.dim}║\n"
        "    ║                                                  "
        "                                ║\n"
        "    ╚══════════════════════════════════════════════════"
        "══════════════════════════════╝\n"
        f"    {Color.reset}"
    )
